name: cubesat-orekit
channels:
  - conda-forge
dependencies:
  - python=3.11
  - orekit
  - numpy
  - pandas
  - matplotlib
  - pytest
  - scikit-learn
  - pytorch
  - plotly
  - tomli
  - pip
  - pip:
      - ppigrf>=1.1.0
